Ergasia: main.o Card.o DeckBuilder.o Follower.o Holding.o Item.o Personality.o Phases.o Player.o
	g++ main.o Card.o DeckBuilder.o Follower.o Holding.o Item.o Personality.o Phases.o Player.o -o Ergasia

main.o: main.cpp
	g++ -c main.cpp

Card.o: Card.cpp
	g++ -c Card.cpp

DeckBuilder.o: DeckBuilder.cpp
	g++ -c DeckBuilder.cpp

Follower.o: Follower.cpp
	g++ -c Follower.cpp

Holding.o: Holding.cpp
	g++ -c Holding.cpp

Item.o: Item.cpp
	g++ -c Item.cpp

Personality.o: Personality.cpp
	g++ -c Personality.cpp

Phases.o: Phases.cpp
	g++ -c Phases.cpp

Player.o: Player.cpp
	g++ -c Player.cpp

clean:
	rm *.o Ergasia
